### ISSUE TITLE
Mailtime not working when deployed 

### ISSUE THREAD

**Issue by yusufola** [VeliovGroup/Mail-Time#11]
Mailtime is working on local but when I deploy using google appengine (nodejs standard environment) and mongodb atlas it doesn't work at all, no collection is created in mongodb.

What could be the cause of this?

Thanks

**Comment by dr-dimitru** [comment]
Hello @yusufola ,

 1. Tell us what versions of nodejs, mongo, node-mongodb-native driver, and nodemailer you're on?
 2. Does local dev environment matches your deployment? 
 3. With could computing (like Heroku, App Engine, Azure), e.g. everything not managed, dedicated, or virtual machine has no solid/continuous runtime, from [google appengine docs](https://cloud.google.com/appengine/docs/flexible/nodejs/how-instances-are-managed):

> Your instances with manual and basic scaling should run indefinitely, but there is no uptime guarantee. Hardware or software failures that cause early termination or frequent restarts can occur without warning and can take considerable time to resolve.

You might want to:
 - [schedule cron task](https://cloud.google.com/appengine/docs/flexible/nodejs/scheduling-jobs-with-cron-yaml)
 - use [web-cron](https://ostr.io/info/web-cron)
 - pick environment with continuous runtime

**Comment by dr-dimitru** [comment]
@yusufola any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
