### ISSUE TITLE
Queue releases very slow

### ISSUE THREAD

**Issue by madonzy** [VeliovGroup/Mail-Time#12]
Hi guys, I have an issue that queue releases very slow (I wait like 3 min on dev server). It works fast without Mail-Time.

Sometimes I get two the same emails in one time. What could be the problem?

**Comment by dr-dimitru** [comment]
Hello @madonzy ,

 1. Are you running on the single-server or multi-server setup?
 2. What's your environment? Linux/Mac/Win?
 3. What's MongoDB version?
 4. Is it plain-vanilla node.js app or Meteor, MEAN, etc.?

**Comment by dr-dimitru** [comment]
Hey @madonzy ,

Any news on your end? Maybe you've found a solution?

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
