### ISSUE TITLE
How about cut email functions off mail-time, just make a common lib.

### ISSUE THREAD

**Issue by fangjj** [VeliovGroup/Mail-Time#15]
### I have a suggestion:
  - mail-time some feature is awesome. like queue, multiple server, retries, strategy, and so on. this should be in sms, crawler, and some async things.  
  - How about cut email functions off mail-time, just make a common lib

**Comment by dr-dimitru** [comment]
Hello @fangjj ,

Very sorry for late reply, I'm glad you've found this library useful.
By the way it's based on top of [`josk` NPM library](https://www.npmjs.com/package/josk) which should be a great fit for tasks you've described. Let me know wdyt.

**Comment by dr-dimitru** [comment]
Closing in favor of #7
