### ISSUE TITLE
maxTries CLI to redispatch email again

### ISSUE THREAD

**Issue by masterbater** [VeliovGroup/Mail-Time#17]
Hi is there any way to redispatch again all failed emails?

**Comment by dr-dimitru** [comment]
Hello @masterbater ,

No, not on current release, this feature will be [merged soon from this PR](https://github.com/VeliovGroup/Mail-Time/pull/16).

Now the only option is to catch failed email is to use a callback of [`.sendMail` method](https://github.com/VeliovGroup/Mail-Time#sendmailopts--callback).

Feel free to close in favor of #16

**Comment by dr-dimitru** [comment]
Closed due to silence (an in favor of #16 PR) at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
