### ISSUE TITLE
mails are stuck in the queue on heroku

### ISSUE THREAD

**Issue by damon-t** [VeliovGroup/Mail-Time#25]
Hi,

I'm using Mail-Time on Meteor 2.3.4 (npm v6.14.13). I've installed the package from atmosphere.
On localhost (windows) everything is working fine like sending mails and keeping them inside the queue until mails are sent.

But if I deploy it to heroku, the mails are stuck in the queue. 
![image](https://user-images.githubusercontent.com/48483164/131649566-eb12e358-2b24-41b5-b23f-485953f33cb3.png)

There are no errors or any other outputs. 

   ```
           mailQueue.sendMail({
                to: recipient,
                cc: this._cc,
                bcc: this._bcc,
                from: this._senderEmail,
                replyTo: this._replyTo,
                messageId: this._messageId,
                inReplyTo: this._inReplyTo,
                references: this._references,
                subject: this._subject,
                html: this._template,
                attachments: this._attachments,
                }, function (err, info) {
                    if (err) {
                        console.log(err.message);
                    } else {
                        console.log(info);
                    }
                });
``` 

Also on the server there are even no console outputs from the callback after running sendMail.

**Comment by dr-dimitru** [comment]
Hello @damon-t ,

It won't work on Heroku or other similar hosting with ephemeral FileSystem and runtime. You need a good server/hosting with continuous runtime.

**Comment by damon-t** [comment]
I am willing to change the hosting, but do you have yet any clue what it could be?

**Comment by dr-dimitru** [comment]
@damon-t any hosting where you can get direct access to Linux; Or hosting with continuous runtime, which basically is remote computer which is running 24/7

Here's [referral link](https://hetzner.cloud/?ref=ePt5Ty6Eo1Tp) to the very good hosting in Germany we use for many years — 
```
https://hetzner.cloud/?ref=ePt5Ty6Eo1Tp
```

**Comment by dr-dimitru** [comment]
Looks solved to me; 
Feel free to reopen it in case if the issue is still persists on your end.

**Comment by dr-dimitru** [comment]
@damon-t let us know if you've manage to migrate to other server and if that solved your issue, thanks
