### ISSUE TITLE
Reduces history

### ISSUE THREAD

**Issue by PeteMac88** [VeliovGroup/Mail-Time#33]
### I have a suggestion:

Would you be open to a PR that slims down the history option a little bit? Currently, the whole email including attachments is kept in the database it's sent when you enable the `keepHistory` flag. I would propose adding an additional setting to drop the attachments to not pollute the database which will keep on growing in size. What do you say?

**Comment by dr-dimitru** [comment]
Hello @PeteMac88 ,

To avoid further tweaks to "history" feature. We can create `onSent` hook where user can decide what to do with sent email object, — save, parse, etc.

**Comment by dr-dimitru** [comment]
@PeteMac88 thoughts?

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
