### ISSUE TITLE
Choose default transporter when sending en email

### ISSUE THREAD

**Issue by sabativi** [VeliovGroup/Mail-Time#38]
Hello,

Thanks for this package, I have a special use case where I have a customer that wants his emails to be sent through his SMTP server only.

I have a multi tenancy app, so I am wondering if I can make choose the default transporter when using sendEmail function ?

Thanks

**Comment by dr-dimitru** [comment]
Hello @sabativi 👋

The solution would be to create multiple `new MailTime` instances. Changing properties of existing instance is possible, but not recommended

**Comment by sabativi** [comment]
Thanks I was thinking about that, can I have two MailTime that uses the same Queue ?
