### ISSUE TITLE
Configuring Mail-Time for Specific Email Sending Rate

### ISSUE THREAD

**Issue by codewishofficial** [VeliovGroup/Mail-Time#39]
### I'm having an issue:
No, just a question

### I have a suggestion:
I have a specific requirement to limit the email sending rate to "X" emails per hour. For instance, 500 emails per hour.

Currently, it's unclear to me how to configure Mail-Time to achieve this specific rate. The `interval` option controls the retry interval, but there doesn't seem to be a direct way to set a limit on the initial email sending rate. Could it be set through `opts.revolvingInterval`?

If not, would the following transport work with MailLite?
```
let transporter = nodemailer.createTransport({
    host: 'smtp.example.com',
    port: 587,
    secure: false,
    auth: {
        user: 'username',
        pass: 'password' 
    },
    pool: true, // Use a single connection pool
    rateLimit: true, // Enable rate limiting
    maxConnections: 1, // Use only one connection
    maxMessages: 500, // Limit to 500 messages per connection
    rateDelta: 3600000, // Rate limit interval (1 hour in milliseconds)
});
```

Thanks.

### Documentation is missing something or incorrect (have typos, etc.):
Not sure, if it is missing in the docs or that I just did not get it.
     
## Thank you for contribution, and do not forget to get rid of this default message

**Comment by dr-dimitru** [comment]
Hello @codewishofficial ,

At the moment there's no build-in `rateLimit` into *MailTime*. I'd suggest to use same option [`node-mailer` pooled SMTP options](https://nodemailer.com/smtp/pooled/) but it seemed to be deprecated.

It would be relatively simple to implement custom rate-limiter as a wrapper for `.sendMail()` method.

I hope that helps

**Comment by codewishofficial** [comment]
Thank you @dr-dimitru 

I'll try the node-mailer option first.
