### ISSUE TITLE
Feature request: Health check function call

### ISSUE THREAD

**Issue by justinlawrence** [VeliovGroup/Mail-Time#42]
Would it be possible for mail-time to create a health check function call or an isReady flag (for use on a /health endpoint).

This would allow us to run mail-time as a microservice and monitor its availability.

In our instance, we would use it on the AWS ECS infrastructure, but this nomenclature seems to be prevalent on other platforms eg.

- https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/monitoring-health-checks.html
- https://learn.microsoft.com/en-us/azure/app-service/monitor-instances-health-check
- https://cloud.google.com/load-balancing/docs/health-check-concepts

**Comment by dr-dimitru** [comment]
@justinlawrence thank you for the great suggestion. `#ping()` method is added in [📦 v3.0.0](https://github.com/veliovgroup/mail-time/releases/tag/3.0.0)

**Comment by justinlawrence** [comment]
Wow wow wow, you guys are on the ball!! 🫶🏻🤯🙌🏻👏🏻

Thank you so much.

**Comment by dr-dimitru** [comment]
@justinlawrence Feel free to close it in case if the issue is solved after testing latest update on your end

**Comment by justinlawrence** [comment]
@dr-dimitru apologies for the delay.

We have just implemented the ping() check into our AWS health checks, and it is working well.

Once again, huge thanks!! 🙌🏻
